package com.didekinlib.gcm.model.common;

import com.didekinlib.model.common.dominio.BeanBuilder;

import java.util.List;

/**
 * User: pedro@didekin
 * Date: 02/06/16
 * Time: 09:12
 */
@SuppressWarnings("WeakerAccess")
public final class GcmMulticastRequest {

    /**
     * This parameter specifies a list of devices (registration tokens, or IDs) receiving a multicast message.
     * It must contain at least 1 and at most 1000 registration tokens.
     * Multicast messages (sending to more than 1 registration tokens) are allowed using HTTP JSON format only.
     * <p/>
     * A registration token is an ID generated by the FCM SDK for each client app instance.   registration_ids
     */
    final String[] registration_ids;
    final GcmRequest gcmRequest;


    public GcmMulticastRequest(Builder builder)
    {
        registration_ids = builder.registration_ids;
        gcmRequest = builder.gcmRequest;
    }

    public String[] getRegistration_ids()
    {
        return registration_ids;
    }

    //    ==================== BUILDER ====================

    @SuppressWarnings("unused")
    public static class Builder implements BeanBuilder<GcmMulticastRequest> {

        private final String[] registration_ids;
        private final GcmRequest gcmRequest;

        @Override
        public GcmMulticastRequest build()
        {
            return new GcmMulticastRequest(this);
        }

        public Builder(List<String> registration_ids, GcmRequest request)
        {
            this.registration_ids = registration_ids.toArray(new String[registration_ids.size()]);
            gcmRequest = request;
        }
    }
}
